# This file defines the content types on the website. See the documentation for
# details: https://docs.bolt.cm/contenttypes/intro

# The Homepage content type is a singleton: There can be only one record of this
# content type.

homepage:
    name: Homepage
    singular_name: Homepage
    fields:
        title:
            type: text
            class: large
            group: content
            localize: true
            label: Title
            postfix: |
                The 'Homepage' can contain basic information about the website. This title will be
                shown on the homepage of the website, as the name implies. To change the
                <em><strong>name</strong></em> of the site, as is shown in the header, and the tab
                in the webbrowser, edit <code>sitename:</code> in the configuration file.
        image:
            type: image
        introduction:
            type: redactor
            localize: true
        apropos:
            type: text
            placeholder: 'A propos de nous titre'
            group: 'A propos'
        apropos_description:
            type: redactor
            label: 'A propos de nous'
        apropos_tagline:
            type: text
        apropos_image:
            type: image
        button_text:
            type: text
        button_url:
            type: text
        blog_title:
            type: text
            label: Titre du blog
            group: Parametres blog
        blog_sub_title:
            type: text
            label: Sous-titre du blog
        services_title:
            type: text
            group: 'Services'
        services_subtitle:
            type: text
        content:
            type: redactor
            localize: true
            group: Autres
        contentlink:
            type: text
            label: Link
            placeholder: 'contentType/slug or https://example.org/'
            postfix: "Use this to add a link for this Homepage. This could either be an 'internal' link like <tt>page//about</tt>, if you use a contentType/slug combination. Otherwise use a proper URL, like `https://example.org`."
            fixture_format: '{url}'
        slug:
            type: slug
            uses: title
            group: Meta
        seo:
            type: seo
            group: "Détails SEO"
    viewless: false
    taxonomy: [ categories, tags, foobars ]
    locales: ['en', 'nl', 'pt_BR', 'es']
    singleton: true
    icon_many: "fa:home"
    icon_one: "fa:home"

# Slider 
Banner:
    name: Banner
    singular_name: Banner
    singleton: true
    viewless: true
    fields:
        title:
            type: text
        description:
            type: text
        sub_title:
            type: text
        button_text:
            type: text
        button_link:
            type: text
        price:
            type: text
        image:
            type: image
            label: image sizes (845 * 810)

Global:
    name: Global
    singular_name: Global
    viewless: true
    singleton: true
    fields:
        sitename:
            type: text
            group: 'A propos du site'
        logo:
            type: image
        about:
            type: redactor
        contact:
            type: collection
            fields:
                phone: 
                    type: text
                email: 
                    type: email
                lieu:
                    type: text

Blog:
    name: Blog
    singular_name: Blog
    record_template: blogitem.twig
    listing_template: blog.twig
    fields:
        title: 
            type: text
            label: Titre
        image:
            type: image
        content:
            type: article
            label: Contenu
        slug:
            type: slug
        seo:
            type: seo
            group: "Détails SEO"

# Services
Services:
    name: Services
    singular_name: Service
    fields:
        title:
            type: text
            label: Title
        image:
            type: image
        content:
            type: redactor
            label: Contenu
        slug:
            type: slug
        seo:
            type: seo
            group: "Détails SEO"

# Products
Articles:
    name: Articles
    singular_name: Article
    fields:
        name:
            type: text
        description:
            type: redactor
        short_description:
            type: redactor
        image:
            type: image
        regular_price:
            type: number
        current_price:
            type: number
        currency:
            type: text
        seo:
            type: seo
            group: "Détails SEO"

# Faqs
Faqs: 
    name: Faqs
    singular_name: Faq
    viewless: true
    viewless_listing: false
    fields:
        question:
            type: text
        answer:
            type: redactor
            label: Réponse
